# Generated by Django 5.2.1 on 2025-06-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='target_language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
