# Generated by Django 5.2.1 on 2025-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0002_audiobook_target_language_audiobook_transcription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='target_language',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='target_languages',
            field=models.CharField(default='en', max_length=200),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='translation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
